watch_stylesheet: true
watch_config: true

bars:
  main-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: "transparent"
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        - "phone_notifications"
      center:
        - "clock"
      right:
        - "volume"
        - "battery"

widgets:
  phone_notifications:
    type: "yasb.custom.CustomWidget"
    options:
      class_name: "custom-widget"
      label: "{data}"
      label_alt: "{data}"
      exec_options:
        run_cmd: "py %USERPROFILE%\\.config\\yasb\\get_latest_notif.py"
        run_interval: 1000
        return_format: "string"
      callbacks:
        on_left: "exec pyw %USERPROFILE%\\.config\\yasb\\show_popup.py --toggle"
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 0

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b %H:%M}"
      label_alt: "{%A %d %B %Y %H:%M:%S}"
      timezones: []
      callbacks:
        on_left: "toggle_label"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "󰕾 {volume}%"
      label_alt: "󰕾 {volume}%"
      volume_icons:
        - "󰝟"
        - "󰕿"
        - "󰖀"
        - "󰕾"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{percent}%"
      label_alt: "{percent}% ({time_remaining})"
      callbacks:
        on_left: "toggle_label"